name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Choose the Node.js version that matches your development environment

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        ARGS: "-avz --delete"
        SOURCE: "next.config.js package.json package-lock.json .next static"
        REMOTE_HOST: "13.124.157.24" # Replace with your EC2 instance's public IP address
        REMOTE_USER: "ec2-user" # Default user for Amazon Linux AMI, replace with your user if different
        #REMOTE_PORT: "22"
        TARGET: "/dadream" # Replace with the path to your app directory on EC2